### ISSUE TITLE
How to build to docs?

### ISSUE THREAD

**Issue by rsbivand** [edzer/UseR2019#2]
How to get knit to build to docs, rather than the working directory?

**Comment by edzer** [comment]
I don't know. I use a makefile that copies, then commits, then pushes.

**Comment by rsbivand** [comment]
OK, but how then do you find resources in docs from root? Or do you copy the Rmd to docs, build, and delete the Rmd from docs?

**Comment by edzer** [comment]
My makefile:
```makefile
push:
	cp -p part1.html docs
	git commit -a -m 'update'
	git push
```
