### ISSUE TITLE
Rendering part 1 fails, starsdata not available

### ISSUE THREAD

**Issue by jspijker** [edzer/UseR2019#4]
Hi Edzer

While preparing for the workshop, I was trying if I could render your markdown documents. I stumbled over the following error while rendering Part1.Rmd:

```
Warning: unable to access index for repository https://cran.uni-muenster.de/pebesma/src/contrib:
  cannot open URL 'https://cran.uni-muenster.de/pebesma/src/contrib/PACKAGES'
Warning message:
package ‘starsdata’ is not available (for R version 3.6.0) 
```
Maybe this is expected behaviour, but just to let you know ;-)

**Comment by edzer** [comment]
Thanks! I believe the section right above it explains how to install it, and warns about doing so (1 Gb, off-CRAN)

**Comment by edzer** [comment]
should run now for other users too; fixed in https://github.com/edzer/UseR2019/commit/8f01a5fbae69bd3b4a6c0232623ee073262a1b9a
