### ISSUE TITLE
starsdata local CRAN download link not working

### ISSUE THREAD

**Issue by angela-li** [edzer/UseR2019#7]
When I run `install.packages("starsdata", repos = "https://cran.uni-muenster.de/pebesma" , type = "source")`

I get the following error message:

`Warning in install.packages :
  unable to access index for repository https://cran.uni-muenster.de/pebesma/src/contrib:
  cannot open URL 'https://cran.uni-muenster.de/pebesma/src/contrib/PACKAGES'`

It looks like the URL for [https://cran.uni-muenster.de/pebesma](https://cran.uni-muenster.de/pebesma) is not available? @edzer

**Comment by edzer** [comment]
Should be:
```r
install.packages("starsdata", repos = "http://gis-bigdata.uni-muenster.de/pebesma" , type = "source")
```

**Comment by angela-li** [comment]
Thanks!
